'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Bank_Of_America_Manager_Checklist

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''bus1_pnr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus1_pnr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus1_lar_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus1_lar_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus1_ala_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus1_ala_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus4_pnr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus4_pnr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus4_lar_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus4_lar_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus4_ala_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus4_ala_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus5_pnr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus5_pnr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus5_lar_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus5_lar_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus5_ala_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus5_ala_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus7_pnr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus7_pnr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus7_lar_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus7_lar_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus7_ala_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus7_ala_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus9_pnr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus9_pnr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus9_lar_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus9_lar_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus9_ala_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus9_ala_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus10_pnr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus10_pnr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus10_lar_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus10_lar_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus10_ala_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus10_ala_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus12_pnr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus12_pnr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus12_lar_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus12_lar_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus12_ala_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus12_ala_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus13_pnr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus13_pnr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus13_lar_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus13_lar_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus13_ala_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus13_ala_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus14_pnr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus14_pnr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus14_lar_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus14_lar_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus14_ala_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus14_ala_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus18_pnr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus18_pnr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus18_lar_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus18_lar_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus18_ala_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus18_ala_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus19_pnr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus19_pnr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus19_lar_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus19_lar_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus19_ala_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus19_ala_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus20_pnr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus20_pnr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus20_lar_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus20_lar_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus20_ala_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus20_ala_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus21_pnr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus21_pnr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus21_lar_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus21_lar_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus21_ala_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus21_ala_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus23_pnr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus23_pnr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus23_lar_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus23_lar_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus23_ala_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus23_ala_cb As Global.System.Web.UI.WebControls.CheckBox
End Class
