'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UPS_Package_Handler_Checklist

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''bus1_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus1_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus1_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus1_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus1_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus1_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus2_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus2_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus2_collectbin_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus2_collectbin_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus2_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus2_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus2_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus2_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus3_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus3_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus3_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus3_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus3_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus3_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus4_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus4_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus4_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus4_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus4_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus4_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus5_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus5_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus5_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus5_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus5_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus5_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus18_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus18_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus18_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus18_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus18_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus18_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus6_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus6_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus6_collectbin_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus6_collectbin_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus6_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus6_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus6_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus6_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus7_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus7_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus7_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus7_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus7_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus7_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus9_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus9_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus9_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus9_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus9_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus9_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus10_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus10_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus10_collectbin_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus10_collectbin_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus10_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus10_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus10_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus10_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus11_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus11_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus11_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus11_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus11_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus11_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus12_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus12_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus12_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus12_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus12_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus12_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus13_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus13_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus13_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus13_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus13_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus13_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus14_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus14_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus14_collectbin_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus14_collectbin_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus14_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus14_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus14_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus14_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus17_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus17_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus17_collectbin_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus17_collectbin_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus17_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus17_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus17_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus17_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox5 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus19_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus19_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus19_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus19_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus19_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus19_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus20_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus20_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus20_collectbin_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus20_collectbin_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus20_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus20_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus20_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus20_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus21_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus21_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus21_collectbin_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus21_collectbin_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus21_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus21_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus21_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus21_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus22_collectbin_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus22_collectbin_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus23_installtherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus23_installtherm_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus23_thankyou_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus23_thankyou_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus23_uninstalltherm_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus23_uninstalltherm_cb As Global.System.Web.UI.WebControls.CheckBox
End Class
