'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class City_Hall_Mayor_Checklist

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''bus1_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus1_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus1_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus1_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus2_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus2_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus2_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus2_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus3_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus3_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus3_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus3_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus4_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus4_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus4_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus4_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus5_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus5_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus5_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus5_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus18_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus18_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus18_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus18_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus6_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus6_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus6_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus6_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus7_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus7_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus7_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus7_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus9_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus9_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus9_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus9_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus10_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus10_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus10_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus10_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus11_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus11_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus11_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus11_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus12_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus12_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus12_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus12_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus13_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus13_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus13_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus13_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus14_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus14_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus14_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus14_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus17_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus17_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus17_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus17_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus19_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus19_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus19_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus19_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus20_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus20_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus20_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus20_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus21_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus21_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus21_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus21_wmr_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus23_wmr_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus23_wmr_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus23_wmr_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus23_wmr_cb As Global.System.Web.UI.WebControls.CheckBox
End Class
