'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Create_Item

    '''<summary>
    '''EMS_Form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EMS_Form As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''headerSchoolName_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents headerSchoolName_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''error_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents error_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''itemName_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents itemName_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''itemCategory_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents itemCategory_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''itemSubCat_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents itemSubCat_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''currentLocation_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents currentLocation_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''businessUsed_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents businessUsed_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''onHand_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents onHand_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''usedDaily_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usedDaily_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''source_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents source_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''merchCode_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents merchCode_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''comments_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comments_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Submit_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''error2_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents error2_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''visitdate_hf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents visitdate_hf As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Review_sds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Review_sds As Global.System.Web.UI.WebControls.SqlDataSource
End Class
