<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="Edit_School.aspx.vb" Inherits="Enterprise_Village_2._0.Edit_School" %>

<!DOCTYPE html>
<html>
<head runat="server">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0; maximum-scale=2.0; user-scalable=0;">

    <title>EV 2.0 - Edit School</title>

    <link href="css/Styles.print.css" rel="stylesheet" media="print" type="text/css">
    <link href="css/Styles.updated.css" rel="stylesheet" media="screen" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="shortcut icon" type="image/png" href="media/EV_favicon_2.png" />
<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
</head>

<body>
    <form id="EMS_Form" runat="server">

        <%--Header information--%>
        <header class="headerTop no-print"><a style="float: left; padding-top: 2px;">Enterprise Village 2.0</a><a style="float: right; padding-right: 30px; padding-top: 2px;"><asp:Label ID="headerSchoolName_lbl" Text="School Name Here" runat="server"></asp:Label></a></header>

      <%--Navigation bar--%>
        <div id="nav-placeholder">

        </div>

        <script>
            $(function () {
                $("#nav-placeholder").load("nav.html");
            });
        </script>

        

        <div class="content">
            <h2 class="h2 no-print">Edit School</h2>
            <h3 class="no-print">This page will allow you to edit a school in the database. Use the drop down menu below to view a specific school. You can also use the textbox under that to search for names, emails, phone numbers, and anything else.
            </h3>
            <p>School Name Drop Down List:</p>
            <asp:DropDownList CssClass="ddl" ID="schoolNameSearch_ddl" runat="server" Width="200px" AutoPostBack="true"></asp:DropDownList> 
            <p>Keyword Search:</p>
            <asp:TextBox ID="search_tb" runat="server" CssClass="textbox"></asp:TextBox> &nbsp;&nbsp; <asp:Button ID="search_btn" runat="server" CssClass="button3" text="Search"/>     
            <br /><br />            
            <asp:Button ID="refresh_btn" runat="server" CssClass="button3" text="Show All Schools"/>
            <br /><br />
            <asp:Label ID="error_lbl" runat="server" ForeColor="Red" Font-Bold="true" Font-Size="X-Large"></asp:Label>
            <br />

            <%--Print Out Table--%>
            <div class="gridviewDiv">
                <asp:GridView ID="school_dgv" runat="server" AutoGenerateColumns="False" PageSize="10" AutoGenerateEditButton="True" AutoGenerateDeleteButton="false" DataKeyNames="ID" CellPadding="3" AllowPaging="True" ShowHeaderWhenEmpty="True" Font-Size="Medium" Visible="true" PagerStyle-CssClass="pager" HeaderStyle-CssClass="header" RowStyle-CssClass="rows">
                    <Columns>
                        <asp:BoundField DataField="ID" HeaderText="ID" Visible="false" />
                        <asp:BoundField DataField="schoolName" HeaderText="School Name" Visible="true" ReadOnly="true" />
                        <%--<asp:TemplateField HeaderText="School Name">
                            <ItemTemplate>
                                <asp:Label id="schoolName_lbl" runat="server" Text='<%#Bind("schoolName") %>' Visible="false"></asp:Label>
                                <asp:DropDownList CssClass="ddl" ID="schoolName_ddl" runat="server" Width="200px" AutoPostBack="true" ReadOnly="false">
                                </asp:DropDownList>
                            </ItemTemplate>                         
                        </asp:TemplateField>--%>
                        <asp:BoundField DataField="currentVisitDate" HeaderText="Current Visit Date" Visible="true" DataFormatString="{0: MM/dd/yyyy } " ReadOnly="true" />
                        <asp:BoundField DataField="previousVisitDate" HeaderText="Previous Visit Date" Visible="true" DataFormatString="{0: MM/dd/yyyy } " ReadOnly="true" />
                        <asp:TemplateField HeaderText="Administrator </br> First Name" >
                            <ItemTemplate>
                                <asp:TextBox ID="principalFirst_tb" runat="server" Width="80px" Text='<%#Bind("principalFirst") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>                         
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Administrator </br> Last Name">
                            <ItemTemplate>
                                <asp:TextBox ID="principalLast_tb" runat="server" Width="80px" Text='<%#Bind("principalLast") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>                         
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Administrator </br> Email">
                            <ItemTemplate>
                                <asp:TextBox ID="futureRequestsEmail_tb" runat="server" Width="200px" Text='<%#Bind("futureRequestsEmail") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField> 
                        <asp:TemplateField HeaderText="Phone #">
                            <ItemTemplate>
                                <asp:TextBox ID="phone_tb" runat="server" Width="95px" Text='<%#Bind("phone") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>                         
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Fax #" Visible="false">
                            <ItemTemplate>
                                <asp:TextBox ID="fax_tb" runat="server" Width="85px" Text='<%#Bind("fax") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>                         
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Hours">
                            <ItemTemplate>
                                <asp:TextBox ID="hours_tb" runat="server" Width="70px" Text='<%#Bind("schoolHours") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>                         
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="School Type">
                            <ItemTemplate>
                                <asp:Label ID="schoolType_lbl" runat="server" Text='<%#Bind("schoolType") %>' Visible="false"></asp:Label>
                                <asp:DropDownList CssClass="ddl" ID="schoolType_ddl" runat="server" Width="100px" AutoPostBack="true" >
                                </asp:DropDownList>
                            </ItemTemplate>                         
                        </asp:TemplateField>                       
                        <%--<asp:TemplateField Headertext="Current Visit Date" Visible="true">
                            <ItemTemplate>
                                <asp:TextBox ID="currentVisitDate_tb" runat="server" Width="80px" Text='<%#Bind("currentVisitDate", "{0:d}") %>' DataFormatString="{0: MM-dd-yyyy } " CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField Headertext="Previous Visit Date" Visible="true">
                            <ItemTemplate>
                                <asp:TextBox ID="previousVisitDate_tb" runat="server" Width="80px" Text='<%#Bind("previousVisitDate", "{0:d}") %>' DataFormatString="{0: MM-dd-yyyy }" CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>--%>                        
                        
                       <asp:TemplateField HeaderText="Address">
                            <ItemTemplate>
                                <asp:TextBox ID="address_tb" runat="server" Width="100px" Text='<%#Bind("address") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="City">
                            <ItemTemplate>
                                <asp:TextBox ID="city_tb" runat="server" Width="100px" Text='<%#Bind("city") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Zip Code">
                            <ItemTemplate>
                                <asp:TextBox ID="zip_tb" runat="server" Width="100px" Text='<%#Bind("zip") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="County">
                            <ItemTemplate>
                                <asp:TextBox ID="county_tb" runat="server" Width="100px" Text='<%#Bind("county") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Liaison">
                            <ItemTemplate>
                                <asp:TextBox ID="liaisonName_tb" runat="server" Width="100px" Text='<%#Bind("liaisonName") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Notes">
                            <ItemTemplate>
                                <asp:TextBox ID="futureRequestsNotes_tb" runat="server" Width="200px" Text='<%#Bind("futureRequests") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        
                    </Columns>
                </asp:GridView>
            </div>
            <br />
        </div>

        <asp:HiddenField ID="visitdate_hf" runat="server" />
        <asp:HiddenField ID="visitdateUpdate_hf" runat="server" />

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="Scripts.js"></script>
        <script>
            /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
            $(".sub-menu ul").hide();
            $(".sub-menu a").click(function () {
                $(this).parent(".sub-menu").children("ul").slideToggle("100");
                $(this).find(".right").toggleClass("fa-caret-up fa-caret-down");
            });
        </script>
        
        <%--Delete confirmation--%>
        <%--<script>
            jQuery("a").filter(function () {
                return this.innerHTML.indexOf("Delete") == 0;
            }).click(function () {
                return confirm("Are you sure you want to delete this teacher?");
            });
        </script>--%>

        <asp:SqlDataSource ID="Review_sds" runat="server"></asp:SqlDataSource>
        <asp:SqlDataSource ID="print_sds" runat="server"></asp:SqlDataSource>
    </form>
</body>
</html>
