'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Mayor_Population_Count

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''bus1_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus1_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus1_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus1_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus2_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus2_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus2_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus2_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus3_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus3_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus3_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus3_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus4_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus4_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus4_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus4_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus5_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus5_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus5_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus5_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus18_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus18_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus18_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus18_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus6_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus6_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus6_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus6_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus7_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus7_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus7_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus7_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus9_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus9_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus9_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus9_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus10_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus10_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus10_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus10_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus11_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus11_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus11_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus11_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus12_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus12_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus12_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus12_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus13_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus13_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus13_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus13_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus14_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus14_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus14_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus14_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus17_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus17_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus17_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus17_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus19_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus19_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus19_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus19_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus20_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus20_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus20_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus20_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus21_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus21_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus21_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus21_bag_cb As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bus23_employees_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus23_employees_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bus23_bag_cb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bus23_bag_cb As Global.System.Web.UI.WebControls.CheckBox
End Class
