<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="Requested_Features.aspx.vb" Inherits="Enterprise_Village_2._0.Requested_Features" %>

<!doctype html>
<html>
<head runat="server">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0; maximum-scale=2.0; user-scalable=0;">

    <title>EV 2.0 - Requested Features and Bug Reports</title>

    <link href="css/Styles.updated.css" rel="stylesheet" media="screen" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="shortcut icon" type="image/png" href="media/EV_favicon_2.png" />

    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
</head>

<body>
    <form id="EMS_Form" runat="server">

        <%--Header information--%>
        <header class="headerTop"><a style="float: left; padding-top: 2px;">Enterprise Village 2.0</a><a style="float: right; padding-right: 30px; padding-top: 2px;"><asp:Label ID="headerSchoolName_lbl" Text="School Name Here" runat="server"></asp:Label></a></header>


        <%--Navigation bar--%>
        <div id="nav-placeholder">
        </div>

        <script>
            $(function () {
                $("#nav-placeholder").load("nav.html");
            });
        </script>

        <%--Content--%>
        <div class="content">
            <h2 class="h2">Requested Features and Bug Reports</h2>
            <h3>This page allows you to submit suggested features and report potential bugs or issues to the technology technician so they can incorporate it into EV 2.0.
            </h3>
            
            <asp:Button ID="createNew_btn" runat="server" CssClass="button3" Text="Create New Post" />&ensp;<asp:Button ID="viewPosts_btn" runat="server" CssClass="button3 no-print" Text="View Posts" />&ensp;<asp:Label ID="error_lbl" runat="server" Font-Bold="true" Font-Size="X-Large" ForeColor="Red"></asp:Label>
            <br />
            
            <%--Create New Posts--%>
            <div id="createNew_div" runat="server" visible="false">
                <p style="color: red;">Notice: When submitting a potential bug, issue, or submitting an idea for EV 2.0, please be as clear and consise as possible. If there's an issue on a page, please name the page the issue is on and what needs to be fixed.</p>
                <p>Issue or Requested Feature:</p>
                <asp:DropDownList ID="type_ddl" runat="server" CssClass="ddl">
                    <asp:ListItem></asp:ListItem>
                    <asp:ListItem>Issue</asp:ListItem>
                    <asp:ListItem>Requested Feature</asp:ListItem>
                </asp:DropDownList>
                <p>Note:</p>
                <asp:TextBox ID="note_tb" runat="server" CssClass="textbox"></asp:TextBox>
                <p>Page Name:</p>
                <asp:Textbox ID="pageName_tb" runat="server" CssClass="textbox"></asp:Textbox>
                <p>Urgency Level:</p>
                <asp:DropDownList ID="urgency_ddl" runat="server" CssClass="ddl">
                    <asp:ListItem>Low</asp:ListItem>
                    <asp:ListItem>Med</asp:ListItem>
                    <asp:ListItem>High</asp:ListItem>
                </asp:DropDownList>
                <br /><br />
                <asp:Button ID="submit_btn" runat="server" CssClass="button3" Text="Submit" />
            </div>

            <%--View Posts--%>
            <div id="viewPosts_div" runat="server" visible="false">
                <br />
                <asp:GridView ID="community_dgv" runat="server" AutoGenerateColumns="False" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" DataKeyNames="ID" CellPadding="5" Height="50" AllowPaging="True" ShowHeaderWhenEmpty="True" Font-Size="Medium" Visible="true" PagerStyle-CssClass="pager" HeaderStyle-CssClass="header" RowStyle-CssClass="rows">
                    <Columns>
                        <asp:BoundField DataField="ID" HeaderText="ID" Visible="false" />
                        <asp:TemplateField HeaderText="Issue or Requested Feature">
                            <ItemTemplate>
                                <asp:Label ID="typeDGV_lbl" runat="server" Text='<%#Bind("type") %>' Visible="false" ReadOnly="true"></asp:Label>
                                <asp:DropDownList CssClass="ddl" ID="typeDGV_ddl" runat="server" ReadOnly="false">
                                    <asp:ListItem></asp:ListItem>
                                    <asp:ListItem>Issue</asp:ListItem>
                                    <asp:ListItem>Requested Feature</asp:ListItem>
                                </asp:DropDownList>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Note">
                            <ItemTemplate>
                                <asp:TextBox ID="noteDGV_tb" runat="server" Width="250px" ReadOnly="false" Text='<%#Bind("communityNote") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Page Name">
                            <ItemTemplate>
                               <asp:TextBox ID="pageNameDGV_tb" runat="server" Width="250px" ReadOnly="false" Text='<%#Bind("pageName") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Urgency Level">
                            <ItemTemplate>
                                <asp:Label ID="urgencyLevelDGV_lbl" runat="server" Text='<%#Bind("urgency") %>' Visible="false" ReadOnly="true"></asp:Label>
                                <asp:DropDownList CssClass="ddl" ID="urgencyLevelDGV_ddl" runat="server" Width="60px" ReadOnly="false">
                                    <asp:ListItem>Low</asp:ListItem>
                                    <asp:ListItem>Med</asp:ListItem>
                                    <asp:ListItem>High</asp:ListItem>
                                </asp:DropDownList>
                            </ItemTemplate>
                        </asp:TemplateField>                         
                        <asp:BoundField DataField="username" HeaderText="Username" Visible="true" ReadOnly="true" />
                        <asp:BoundField DataField="timestamp" HeaderText="Timestamp" Visible="true" ReadOnly="true" />
                        <asp:TemplateField HeaderText="Page Name" Visible="false">
                            <ItemTemplate>
                               <asp:TextBox ID="usernameDGV_tb" runat="server" Width="250px" ReadOnly="true" Text='<%#Bind("username") %>' CssClass="textbox" Visible="false"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Resolved?" Visible="true">
                            <ItemTemplate>
                               <asp:Checkbox ID="resolved_chk" runat="server" ReadOnly="false" Visible="true"></asp:Checkbox>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>
            </div>
        </div>

        <asp:HiddenField ID="currentVisitID_hf" runat="server" />

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="Scripts.js"></script>
        <script>
            /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
            $(".sub-menu ul").hide();
            $(".sub-menu a").click(function () {
                $(this).parent(".sub-menu").children("ul").slideToggle("100");
                $(this).find(".right").toggleClass("fa-caret-up fa-caret-down");
            });
        </script>

        <asp:SqlDataSource ID="Review_sds" runat="server"></asp:SqlDataSource>
    </form>
</body>
</html>
