'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Visit_Calendar

    '''<summary>
    '''EMS_Form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EMS_Form As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''headerSchoolName_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents headerSchoolName_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''month_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents month_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''error_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents error_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''calendarView_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendarView_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''monday1_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday1_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''monday1School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday1School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday1School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday1School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday1School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday1School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday1School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday1School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday1School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday1School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday1_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday1_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tuesday1School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday1School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday1School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday1School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday1School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday1School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday1School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday1School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday1School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday1School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday1_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday1_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''wednesday1School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday1School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday1School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday1School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday1School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday1School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday1School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday1School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday1School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday1School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday1_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday1_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''thursday1School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday1School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday1School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday1School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday1School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday1School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday1School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday1School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday1School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday1School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday1_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday1_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''friday1School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday1School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday1School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday1School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday1School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday1School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday1School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday1School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday1School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday1School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday2_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday2_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''monday2School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday2School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday2School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday2School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday2School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday2School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday2School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday2School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday2School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday2School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday2_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday2_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tuesday2School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday2School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday2School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday2School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday2School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday2School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday2School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday2School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday2School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday2School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday2_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday2_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''wednesday2School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday2School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday2School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday2School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday2School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday2School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday2School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday2School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday2School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday2School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday2_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday2_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''thursday2School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday2School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday2School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday2School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday2School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday2School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday2School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday2School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday2School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday2School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday2_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday2_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''friday2School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday2School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday2School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday2School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday2School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday2School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday2School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday2School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday2School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday2School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday3_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday3_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''monday3School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday3School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday3School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday3School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday3School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday3School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday3School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday3School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday3School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday3School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday3_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday3_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tuesday3School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday3School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday3School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday3School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday3School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday3School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday3School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday3School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday3School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday3School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday3_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday3_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''wednesday3School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday3School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday3School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday3School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday3School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday3School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday3School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday3School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday3School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday3School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday3_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday3_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''thursday3School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday3School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday3School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday3School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday3School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday3School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday3School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday3School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday3School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday3School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday3_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday3_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''friday3School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday3School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday3School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday3School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday3School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday3School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday3School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday3School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday3School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday3School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday4_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday4_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''monday4School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday4School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday4School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday4School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday4School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday4School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday4School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday4School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday4School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday4School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday4_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday4_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tuesday4School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday4School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday4School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday4School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday4School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday4School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday4School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday4School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday4School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday4School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday4_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday4_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''wednesday4School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday4School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday4School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday4School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday4School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday4School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday4School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday4School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday4School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday4School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday4_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday4_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''thursday4School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday4School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday4School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday4School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday4School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday4School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday4School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday4School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday4School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday4School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday4_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday4_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''friday4School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday4School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday4School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday4School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday4School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday4School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday4School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday4School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday4School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday4School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday5_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday5_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''monday5School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday5School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday5School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday5School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday5School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday5School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday5School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday5School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''monday5School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monday5School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday5_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday5_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tuesday5School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday5School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday5School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday5School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday5School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday5School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday5School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday5School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tuesday5School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuesday5School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday5_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday5_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''wednesday5School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday5School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday5School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday5School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday5School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday5School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday5School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday5School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wednesday5School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wednesday5School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday5_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday5_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''thursday5School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday5School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday5School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday5School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday5School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday5School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday5School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday5School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''thursday5School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thursday5School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday5_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday5_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''friday5School1_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday5School1_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday5School2_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday5School2_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday5School3_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday5School3_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday5School4_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday5School4_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''friday5School5_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friday5School5_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''currentVisitID_hf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents currentVisitID_hf As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Review_sds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Review_sds As Global.System.Web.UI.WebControls.SqlDataSource
End Class
