'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Print_Teller

    '''<summary>
    '''Online_Banking_Form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Online_Banking_Form As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''name_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents name_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''account_number_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents account_number_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''balance_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents balance_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''savings_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents savings_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''checkAmount_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkAmount_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cash_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cash_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''netDeposit_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents netDeposit_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''newBalance_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newBalance_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''deposit1_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deposit1_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''deposit2_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deposit2_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''deposit3_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deposit3_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''deposit4_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deposit4_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Check_amount_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_amount_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cash_recieved_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cash_recieved_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''date_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents date_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''empnum_hf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents empnum_hf As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''visitDate_hf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents visitDate_hf As Global.System.Web.UI.WebControls.HiddenField
End Class
