'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Print_Sales

    '''<summary>
    '''Online_Banking_Form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Online_Banking_Form As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''name_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents name_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''account_number_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents account_number_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''balance_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents balance_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''newBalance_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newBalance_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''item1_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents item1_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''item2_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents item2_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''item3_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents item3_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''item4_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents item4_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''saleTotal_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents saleTotal_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''date_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents date_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''empnum_hf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents empnum_hf As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''visitDate_hf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents visitDate_hf As Global.System.Web.UI.WebControls.HiddenField
End Class
