'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Volunteer_Database

    '''<summary>
    '''EMS_Form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EMS_Form As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''headerSchoolName_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents headerSchoolName_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''visitDate_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents visitDate_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''schoolName_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolName_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''businessAssignments_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents businessAssignments_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''refresh_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents refresh_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''error_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents error_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''visitDate_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents visitDate_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''visitDateSchools_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents visitDateSchools_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''visitDate_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents visitDate_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''visitDateSchools_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents visitDateSchools_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''schoolName_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolName_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''schoolVisitDate_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolVisitDate_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''schoolName_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolName_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''schoolVisitDate_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolVisitDate_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''buttons_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buttons_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''addVol_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addVol_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''checkIn_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkIn_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''addVol_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addVol_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''addVolDate_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addVolDate_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''addVolBiz_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addVolBiz_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''visitDateVol_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents visitDateVol_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''addVolSpace_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addVolSpace_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''businessName_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents businessName_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''firstName_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents firstName_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lastName_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lastName_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pr_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pr_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''svHours_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents svHours_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''regularVol_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regularVol_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''notes_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notes_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''submit_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submit_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''totalSVHours_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents totalSVHours_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''checkIn_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkIn_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ach_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ach_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ach1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ach1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ach2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ach2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ach3_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ach3_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ach4_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ach4_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolAch_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolAch_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cvs_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvs_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''cvs1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvs1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cvs2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvs2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cvs3_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvs3_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolCVS_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolCVS_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pcsw_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcsw_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''pcsw1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcsw1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pcsw2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcsw2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolPCSW_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolPCSW_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''astro_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents astro_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''astro1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents astro1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''astro2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents astro2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolAstro_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolAstro_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ditek_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ditek_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ditek1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ditek1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ditek2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ditek2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolDitek_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolDitek_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''know_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents know_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''know1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents know1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''know2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents know2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolKnow_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolKnow_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''baycare_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents baycare_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''baycare1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents baycare1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''baycare2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents baycare2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolBaycare_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolBaycare_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''duke_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents duke_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''duke1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents duke1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''duke2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents duke2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolDuke_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolDuke_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''bucs_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bucs_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''bucs1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bucs1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bucs2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bucs2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolBucs_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolBucs_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''bbb_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bbb_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''bbb1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bbb1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bbb2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bbb2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolBBB_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolBBB_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hsn_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hsn_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''hsn1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hsn1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''hsn2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hsn2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolHSN_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolHSN_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rays_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rays_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''rays1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rays1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''rays2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rays2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''rays3_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rays3_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolRays_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolRays_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''bic_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bic_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''bic1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bic1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bic2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bic2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bic3_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bic3_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolBic_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolBic_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''kanes_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents kanes_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''kanes1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents kanes1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''kanes2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents kanes2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolKanes_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolKanes_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''times_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents times_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''times1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents times1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''times2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents times2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''times3_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents times3_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolTimes_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolTimes_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''city_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents city_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''city1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents city1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''city2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents city2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''city3_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents city3_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolCity_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolCity_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''mcdonalds_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mcdonalds_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mcd1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mcd1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''mcd2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mcd2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''mcd3_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mcd3_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolMcdonalds_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolMcdonalds_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''td_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''td1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''td2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''td3_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td3_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolTD_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolTD_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''mix_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mix_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mix1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mix1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''mix2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mix2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolMix_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolMix_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''united_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents united_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''uw1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uw1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''uw2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uw2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''uw3_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uw3_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolUnited_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolUnited_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pcu_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcu_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''pcu1_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcu1_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pcu2_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcu2_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolPCU_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolPCU_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ups_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ups_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ups_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ups_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolUPS_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolUPS_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dali_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dali_a As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''dali_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dali_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''regVolDali_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regVolDali_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''submitCheckIn_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submitCheckIn_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''viewVol_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewVol_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''search_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents search_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''search_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents search_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''sortBy_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sortBy_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ascDesc_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ascDesc_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''sortBy_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sortBy_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''volunteers_dgv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents volunteers_dgv As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''businessCount_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents businessCount_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''currentVisitID_hf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents currentVisitID_hf As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Review_sds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Review_sds As Global.System.Web.UI.WebControls.SqlDataSource
End Class
