<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="Edit_Teacher.aspx.vb" Inherits="Enterprise_Village_2._0.Edit_Teacher" %>

<!DOCTYPE html>
<html>
<head runat="server">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0; maximum-scale=2.0; user-scalable=0;">

    <title>EV 2.0 - Edit Teacher</title>

    <link href="~/css/Styles.print.css" rel="stylesheet" media="print" type="text/css">
    <link href="~/css/Styles.updated.css" rel="stylesheet" media="screen" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="shortcut icon" type="image/png" href="~/media/EV_favicon_2.png" />
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
</head>

<body>
    <form id="EMS_Form" runat="server">

        <%--Header information--%>
        <header class="headerTop no-print"><a style="float: left; padding-top: 2px;">Enterprise Village 2.0</a><a style="float: right; padding-right: 30px; padding-top: 2px;"><asp:Label ID="headerSchoolName_lbl" Text="School Name Here" runat="server"></asp:Label></a></header>

    <%--Navigation bar--%>
        <div id="nav-placeholder">

        </div>

        <script>
            $(function () {
                $("#nav-placeholder").load("../../nav.html");
            });
        </script>    

        <div class="content">
            <h2 class="h2 no-print">Edit Teachers</h2>
            <h3 class="no-print">This page displays all teachers in the database. Select the school the teacher belongs to from the drop down menu below.
                <%--The password criteria is the school name + county name (Example: gullettmanatee) --%>
            </h3>
            <p>School Name:</p>
            <asp:DropDownList CssClass="ddl" ID="schoolName_ddl" runat="server" AutoPostBack="true"></asp:DropDownList> &ensp;<asp:Label ID="error_lbl" runat="server" ForeColor="Red" Font-Size="X-Large"></asp:Label>            
            <p>Keyword Search:</p>
            <asp:TextBox ID="search_tb" runat="server" CssClass="textbox" Width="200px"></asp:TextBox> <asp:Button ID="search_btn" runat="server" CssClass="button3" text="Search"/>&ensp;|&ensp;<asp:Button ID="refresh_btn" runat="server" CssClass="button3" Text="Refresh" />
            <br /><br />

             <%--Print Out Table--%>           <%--style="overflow-x:scroll; width: 70%; overflow-y: scroll;"--%>
            <div class="gridviewDiv" >
                <asp:GridView ID="teachers_dgv" runat="server" AutoGenerateColumns="False" AutoGenerateEditButton="True" AutoGenerateDeleteButton="true" DataKeyNames="ID" CellPadding="5" Height="50" PageSize="11" AllowPaging="True" ShowHeaderWhenEmpty="True" Font-Size="Medium" Visible="true" PagerStyle-CssClass="pager" HeaderStyle-CssClass="header" RowStyle-CssClass="rows">
                    <Columns>
                        <asp:BoundField DataField="ID" HeaderText="ID" Visible="false" />
                        <asp:TemplateField HeaderText="School Name">
                            <ItemTemplate>
                                <asp:Label id="schoolName_lbl" runat="server" Text='<%#Bind("schoolName") %>' Visible="false"></asp:Label>
                                <asp:DropDownList CssClass="ddl" ID="schoolName_ddl" runat="server" Width="200px" AutoPostBack="true" ReadOnly="false">
                                </asp:DropDownList>
                            </ItemTemplate>                         
                        </asp:TemplateField>
                        <asp:TemplateField Headertext="First Name">
                            <ItemTemplate>
                                <asp:TextBox ID="firstName_tb" runat="server" Width="80px" Text='<%#Bind("firstName") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Last Name">
                            <ItemTemplate>
                                <asp:TextBox ID="lastName_tb" runat="server" Width="80px" Text='<%#Bind("lastName") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Teacher <br/> Email">
                            <ItemTemplate>
                                <asp:TextBox ID="futureRequestsEmail_tb" runat="server" Width="200px" Text='<%#Bind("futureRequestsEmail") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Password" Visible="true">
                            <ItemTemplate>
                                <asp:TextBox ID="password_tb" runat="server" Width="80px" Text='<%#Bind("password") %>' Visible="true" CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="County">
                            <ItemTemplate>
                                <asp:TextBox ID="county_tb" runat="server" Width="80px" Text='<%#Bind("county") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Student <br/> Count">
                            <ItemTemplate>
                                <asp:TextBox ID="studentCount_tb" runat="server" Width="60px" Text='<%#Bind("studentCount") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Contact <br/> Teacher?">
                            <ItemTemplate>
                                <asp:CheckBox ID="contact_chk" runat="server" Checked='<%#Bind("isContact") %>' />
                            </ItemTemplate>
                        </asp:TemplateField>
                        
                    </Columns>
                </asp:GridView>
                <br />
            </div>           
        </div>
        
        <asp:HiddenField ID="visitdate_hf" runat="server" />
        <asp:HiddenField ID="teachers_hf" runat="server" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="../../Scripts.js"></script>
        <script>
            /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
            $(".sub-menu ul").hide();
            $(".sub-menu a").click(function () {
                $(this).parent(".sub-menu").children("ul").slideToggle("100");
                $(this).find(".right").toggleClass("fa-caret-up fa-caret-down");
            });
        </script>

        <%--Delete confirmation--%>
        <script>
            jQuery("a").filter(function () {
                return this.innerHTML.indexOf("Delete") == 0;
            }).click(function () {
                return confirm("Are you sure you want to delete this teacher?");
            });
        </script>

        <asp:SqlDataSource ID="Review_sds" runat="server"></asp:SqlDataSource>
        <asp:SqlDataSource ID="print_sds" runat="server"></asp:SqlDataSource>
    </form>
</body>
</html>

