'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EV_Daily_Forms

    '''<summary>
    '''EMS_Form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EMS_Form As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''headerSchoolName_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents headerSchoolName_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''StavrosLogo_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StavrosLogo_img As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''visitDate_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents visitDate_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''error_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents error_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''schoolName_p control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolName_p As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''schoolName_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolName_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''printPCSB_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents printPCSB_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''info_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents info_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''title_h3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents title_h3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''visitDate_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents visitDate_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PCSBForms_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PCSBForms_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''schoolName_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolName_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lunchPCSB_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lunchPCSB_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''workbooksOOC_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents workbooksOOC_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''schoolName2_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolName2_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''workbooks_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents workbooks_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''questions_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents questions_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''questionsOOC_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents questionsOOC_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''EVLogo_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EVLogo_img As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''visitdate_hf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents visitdate_hf As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''businessID_hf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents businessID_hf As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''teacherID_hf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents teacherID_hf As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''schoolID_hf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolID_hf As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''schoolType_hf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolType_hf As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Review_sds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Review_sds As Global.System.Web.UI.WebControls.SqlDataSource
End Class
