'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Teacher_Letter

    '''<summary>
    '''EMS_Form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EMS_Form As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''headerSchoolName_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents headerSchoolName_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''visitDate_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents visitDate_tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''error_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents error_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''school_p control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents school_p As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''schoolName_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolName_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''teacher_p control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents teacher_p As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''teacherName_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents teacherName_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''print_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents print_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''info_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents info_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''schoolName_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolName_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''visitDate_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents visitDate_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''studentArrivalTime_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents studentArrivalTime_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''studentDismissalTime_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents studentDismissalTime_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''sharingSchool_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sharingSchool_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''schoolName2_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolName2_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''schoolName3_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolName3_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''schoolName4_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolName4_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''schoolName5_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolName5_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''sharingSchoolString_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sharingSchoolString_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''teacherName_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents teacherName_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''studentCount_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents studentCount_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ach_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ach_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cvs_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvs_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pcsw_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcsw_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''astro_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents astro_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ditek_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ditek_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''know_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents know_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''baycare_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents baycare_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''duke_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents duke_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bucs_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bucs_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bbb_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bbb_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''hsn_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hsn_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''rays_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rays_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bic_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bic_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''kanes_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents kanes_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''times_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents times_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''city_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents city_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''mcdonalds_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mcdonalds_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''td_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''mix_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mix_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''united_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents united_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pcu_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcu_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ups_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ups_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''dali_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dali_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''inCountyLetter_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inCountyLetter_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''vTrainingTime_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vTrainingTime_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''vMin_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vMin_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''vMax_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vMax_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''replyBy_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents replyBy_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''outOfCountyLetter_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents outOfCountyLetter_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''vTrainingTime2_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vTrainingTime2_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''vMin2_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vMin2_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''vMax2_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vMax2_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''replyBy2_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents replyBy2_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''businessCount_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents businessCount_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''visitdate_hf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents visitdate_hf As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''businessID_hf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents businessID_hf As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''teacherID_hf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents teacherID_hf As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''schoolID_hf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolID_hf As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''schoolType_hf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolType_hf As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Review_sds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Review_sds As Global.System.Web.UI.WebControls.SqlDataSource
End Class
