<%@ Page Language="vb" AutoEventWireup="false" EnableEventValidation="true" CodeBehind="Badge_Creator_History.aspx.vb" Inherits="Enterprise_Village_2._0.Badge_Creator_History" %>

<!DOCTYPE html>

<html>
<head runat="server">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0; maximum-scale=2.0; user-scalable=0;">

    <title class="no-print">Badge History</title>

    <link href="~/css/Styles.Print.css" rel="stylesheet" media="print" type="text/css">
    <link href="~/css/Styles.profit.css" rel="stylesheet" media="screen" type="text/css">
    <link rel="shortcut icon" type="image/png" href="~/media/EV_favicon_2.png" />

    <script src="script-jquery-3.6.0.slim.js"></script>
    <script src="jquery.webcam.js"></script>
    <script src="../../Scripts.js"></script>

    <style>
        #container {
            margin: 0px auto;
            width: 50px;
            height: 37px;
            border: 10px #333 solid;
            float: right;
        }

        #videoElement {
            margin: 10px auto;
            width: 110px;
            height: 125px;
            background-color: white;
            float: right;
        }

        .d-none {
        }
    </style>
    <script>
        function redirect() {
            window.location.href = "https://ev.pcsb.org/pages/student/Badge_creator.aspx";
        }
    </script>
</head>

<body>
    <form id="Profit_display_Form" runat="server">
        <div id="site_wrap">
            <div class="main_mix">
                <asp:Label ID="Label19" runat="server" Text="Badge History" Font-Size="70px" CssClass="no-print"></asp:Label>
                <br />
                <asp:LinkButton ID="LinkButton9" runat="server" PostBackUrl="/pages/student/badge_creator_print.aspx" Font-Size="Medium" CssClass="button button1">Print Badges</asp:LinkButton>
                <asp:LinkButton ID="LinkButton1" runat="server" PostBackUrl="/pages/student/badge_creator.aspx" Font-Size="Medium" CssClass="button button1">Badge Creator</asp:LinkButton>
                <br /><br />

                <%--Searching section--%>
                <div id="searchingSection_div" runat="server" visible="true">
                    <p style="font-size: 15px; font-weight: bold; text-decoration: underline; margin: 10px;">Select a student name from the list below:</p>
                    <asp:DropDownList ID="studentSearch_ddl" runat="server" CssClass="ddl" AutoPostBack="false"></asp:DropDownList>
                    &nbsp;&nbsp;
                    <asp:Button ID="search_btn" runat="server" CssClass="button4" Text="Search" Visible="true" />
                    &nbsp;&nbsp;
                    <asp:Button ID="reset_btn" runat="server" CssClass="button4" Text="Reset" Visible="true" />
                </div>
                <br />

                <%--Delete section--%>
                <div id="delete_div" runat="server" visible="false">
                    <p style="font-size: 30px; font-weight: bold; text-decoration: underline; margin: 5px;">Are you sure you want to delete
                        <asp:Label ID="deletingName_lbl" runat="server"></asp:Label>'s badge?</p>
                    <p style="font-size: 20px; font-weight: bold; margin: 10px;">Type in 'Delete' to delete the selected badge.</p>
                    <asp:TextBox ID="deleteConfirm_tb" runat="server" Width="90px"></asp:TextBox>
                    &ensp;<asp:Button ID="deleteConfirm_btn" runat="server" Text="Delete" CssClass="delete_button" />
                    &ensp;<asp:Button ID="cancel_btn" runat="server" CssClass="button4" Text="Cancel" />
                </div>

                <br />
                <asp:Label ID="error_lbl" runat="server" Font-Size="Large" ForeColor="Yellow"></asp:Label>
                <br />
                <br />

                <%--All saved Badges--%>
                <div>
                    <asp:GridView ID="existingBadges_dgv" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="true" DataKeyNames="ID" AllowPaging="True" CellPadding="5" Font-Size="Medium" Height="50px" AlternatingRowStyle-HorizontalAlign="Center" HorizontalAlign="Center" BorderColor="Black" CssClass="no-print" PageSize="4">
                        <%--<RowStyle BackColor="White" />--%>
                        <Columns>
                            <asp:BoundField DataField="ID" HeaderText="ID" ReadOnly="true" Visible="false" />
                            <asp:BoundField DataField="employeeNumber" HeaderText="Employee Number" ReadOnly="true" Visible="true" />
                            <asp:BoundField DataField="employeeName" HeaderText="Name" ReadOnly="true" Visible="true" />
                            <asp:BoundField DataField="businessName" HeaderText="Business Assigned" ReadOnly="true" Visible="true" />
                            <asp:BoundField DataField="jobTitle" HeaderText="Job" ReadOnly="true" Visible="true" />
                            <asp:ImageField DataImageUrlField="photoPath" ControlStyle-Width="100" ControlStyle-Height="100" HeaderText="Photo">
                                <ControlStyle Height="100px" Width="100px"></ControlStyle>
                            </asp:ImageField>
                        </Columns>
                    </asp:GridView>
                </div>

            </div>
            <asp:HiddenField ID="visitdate_hf" runat="server" />
            <asp:HiddenField ID="deletingID_hf" runat="server" />
            <asp:HiddenField ID="deletingName_hf" runat="server" />
            <asp:GridView ID="printBadges_dgv" runat="server" PageSize="100" Visible="true" ShowHeaderWhenEmpty="True" CssClass="no-print"></asp:GridView>
        </div>
    </form>

</body>
</html>
